# SPDX-FileCopyrightText: 2026 ludable
# SPDX-License-Identifier: AGPL-3.0-only

import importlib.util
from pathlib import Path
import unittest


PROJECT_ROOT = Path(__file__).resolve().parent.parent
SPEC = importlib.util.spec_from_file_location(
    "build_web", PROJECT_ROOT / "scripts/build_web.py"
)
build_web = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(build_web)


class BuildWebTest(unittest.TestCase):
    def test_generated_pages_have_one_aggregate_spdx_header(self):
        pages = sorted(build_web.SRC_DIR.rglob("index.html"))
        self.assertTrue(pages)

        for page in pages:
            with self.subTest(page=page.relative_to(build_web.SRC_DIR)):
                output = build_web.inline_html(page)
                lines = output.splitlines()

                self.assertTrue(lines[0].lower().startswith("<!doctype"))
                self.assertIn("Generated by scripts/build_web.py", lines[1])
                # The initial-publication year is fixed; see inline_html().
                self.assertEqual(
                    lines[2], "<!-- SPDX-FileCopyrightText: 2026 ludable -->"
                )
                self.assertEqual(
                    lines[3],
                    "<!-- SPDX-License-Identifier: AGPL-3.0-only -->",
                )
                self.assertEqual(output.count("SPDX-FileCopyrightText:"), 1)
                self.assertEqual(output.count("SPDX-License-Identifier:"), 1)
                self.assertNotIn("// SPDX-", output)


if __name__ == "__main__":
    unittest.main()
