// SPDX-FileCopyrightText: 2026 ludable
// SPDX-License-Identifier: AGPL-3.0-only

#pragma once

#include <string_view>

namespace net {

// WebServer URL-decodes query arguments before applying the policy. Keep the
// generated query value beside the decoded destination it represents.
inline constexpr char kPairHomeDestination[] = "/";
inline constexpr char kPairConfigDestination[] = "/config/#paired";
inline constexpr char kPairConfigDestinationEncoded[] = "/config/%23paired";
inline constexpr char kPairFailureDestination[] = "/config/";

// Failed pairing returns to the PIN form. Successful QR pairing accepts only
// the destinations generated by the firmware, so browser path normalization
// cannot turn a crafted destination into an external redirect.
inline const char* pairRedirectDestination(bool paired,
                                           std::string_view requested) {
  if (!paired) return kPairFailureDestination;
  if (requested == kPairHomeDestination) return kPairHomeDestination;
  if (requested == kPairConfigDestination) return kPairConfigDestination;
  return kPairHomeDestination;
}

}  // namespace net
