# SPDX-FileCopyrightText: 2026 ludable
# SPDX-License-Identifier: AGPL-3.0-only

"""Pre-build: gzip every file under web/ and emit src/net/embedded_assets.{h,cpp}.

The generated table is consumed by HttpServer, which serves each blob with
Content-Encoding: gzip. URL paths mirror the layout under web/, e.g.
web/config/index.html -> /config/index.html.

Outputs are only rewritten when the inputs change (tracked via a stamp file)
so incremental builds don't churn. The generator is part of that input: changing
its output format must invalidate the stamp.
"""

import gzip
import hashlib
from pathlib import Path

Import("env")  # noqa: F821  (PlatformIO injects this)

PROJECT_DIR = Path(env["PROJECT_DIR"])  # noqa: F821
WEB_DIR = PROJECT_DIR / "web"
OUT_DIR = PROJECT_DIR / "src" / "net"
OUT_H = OUT_DIR / "embedded_assets.h"
OUT_CPP = OUT_DIR / "embedded_assets.cpp"
STAMP = OUT_DIR / ".embedded_assets.stamp"
# Resolve through PROJECT_DIR because PlatformIO executes this file without
# defining __file__.
SELF = PROJECT_DIR / "scripts" / "embed_web.py"

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".mjs": "application/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".woff2": "font/woff2",
    ".woff": "font/woff",
    ".txt": "text/plain; charset=utf-8",
    ".map": "application/json; charset=utf-8",
}


def content_type_for(name: str) -> str:
    return CONTENT_TYPES.get(Path(name).suffix.lower(), "application/octet-stream")


def gather_assets():
    if not WEB_DIR.is_dir():
        return []
    found = []
    for path in sorted(WEB_DIR.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(WEB_DIR).as_posix()
        found.append((rel, path))
    return found


def compute_hash(assets) -> str:
    h = hashlib.sha256()
    h.update(SELF.read_bytes())
    h.update(b"\0")
    for rel, path in assets:
        h.update(rel.encode("utf-8"))
        h.update(b"\0")
        h.update(path.read_bytes())
        h.update(b"\0")
    return h.hexdigest()


def c_ident(rel: str) -> str:
    return "asset_" + "".join(ch if ch.isalnum() else "_" for ch in rel)


def format_bytes(data: bytes, indent: str = "    ") -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append(indent + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def generate(assets) -> int:
    """Write the .h/.cpp files. Returns total compressed bytes embedded."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    header = [
        "// Auto-generated by scripts/embed_web.py. Do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "struct EmbeddedAsset {",
        "  const char* path;          // e.g. /config/index.html",
        "  const uint8_t* data;       // gzip-compressed, PROGMEM",
        "  size_t size;               // compressed size in bytes",
        "  const char* content_type;",
        "};",
        "",
        "extern const EmbeddedAsset kEmbeddedAssets[];",
        "extern const size_t kEmbeddedAssetCount;",
        "",
    ]
    OUT_H.write_text("\n".join(header))

    cpp = [
        "// Auto-generated by scripts/embed_web.py. Do not edit.",
        "",
        '#include "embedded_assets.h"',
        "",
        "#include <pgmspace.h>",
        "",
    ]

    entries = []
    for rel, path in assets:
        raw = path.read_bytes()
        compressed = gzip.compress(raw, mtime=0)
        ident = c_ident(rel)
        entries.append((rel, ident, len(compressed), content_type_for(rel)))
        cpp.append(f"static const uint8_t {ident}[] PROGMEM = {{")
        cpp.append(format_bytes(compressed))
        cpp.append("};")
        cpp.append("")

    cpp.append("const EmbeddedAsset kEmbeddedAssets[] = {")
    for rel, ident, size, ctype in entries:
        cpp.append(f'    {{"/{rel}", {ident}, {size}, "{ctype}"}},')
    cpp.append("};")
    cpp.append("")
    cpp.append(f"const size_t kEmbeddedAssetCount = {len(entries)};")
    cpp.append("")

    OUT_CPP.write_text("\n".join(cpp))
    return sum(size for _, _, size, _ in entries)


def main() -> None:
    assets = gather_assets()
    current_hash = compute_hash(assets)
    stale = (
        not STAMP.exists()
        or STAMP.read_text().strip() != current_hash
        or not OUT_H.exists()
        or not OUT_CPP.exists()
    )
    if not stale:
        return
    total = generate(assets)
    STAMP.write_text(current_hash + "\n")
    print(f"[embed_web] embedded {len(assets)} asset(s), {total} compressed bytes")


main()
